config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :registrations, only: %i[new create]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :account_settings, only: %i[index] do
    delete '/destroy', action: 'destroy', on: :collection
  end

  resources :locations, only: %i[index] do
    get '/following', action: 'following', on: :collection
    get '/follow/:id', action: 'follow', on: :collection, as: :follow
    delete '/unfollow/:id', action: 'unfollow', on: :collection, as: :unfollow
  end

  root to: 'static_pages#home'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
# frozen_string_literal: true

class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :location

  validates :location_id, uniqueness: { scope: :user_id }
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  attr_accessor :weather
  validates :api_id, :name, :country,
            presence: true

  self.per_page = 10

  has_many :follows
  has_many :users, through: :follows

  scope :not_subscribed_by_user, ->(query, user) {
                                  where.not(id: Follow.select(:location_id).where(user_id: user ))
                                       .where('lower(locations.name) LIKE ?', "#{query.try(:downcase)}%") }
  def belongs_to_user?(user)
    Follow.find_by(location: self, user: user).present?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

  validates :username, presence: true, uniqueness: true

  validates :password, presence: true, on: :create
  validates :password, confirmation: { case_sensitive: true }
  validates :password, length: { minimum: 8 }, allow_blank: true

  has_many :follows, dependent: :delete_all
  has_many :locations, through: :follows
end

app/controllers/account_settings_controller.rb
# frozen_string_literal: true

class AccountSettingsController < ApplicationController
  before_action :authenticate_user

  def index; end

  def destroy
    current_user.destroy
    reset_session
    flash[:success] = t('account_settings.index.remove_message')
    redirect_to root_path
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base

  def authenticate_user
    redirect_to root_path unless current_user
  end

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/locations_controller.rb
# frozen_string_literal: true

class LocationsController < ApplicationController
  before_action :authenticate_user
  before_action :set_location, only: :follow
  before_action :set_follow, only: :unfollow
  def index
    query = params[:query].try(:downcase)
    @locations = Location.not_subscribed_by_user(query, current_user)
                         .page(params[:page])
  end

  def following
    @locations = current_user.locations
    api = OpenWeatherMap::CurrentWeather.new(ENVied.OPEN_WEATHER_API_KEY)
    @locations.each do |location|
      location.weather = api.city_by_id(location.api_id)
    end
  end

  def follow
    if current_user.locations << @location
      flash[:success] = t('locations.follow.success')
    else
      flash[:danger] = t('locations.follow.failure')
    end
    redirect_to following_locations_path
  end

  def unfollow
    if @follow.destroy
      flash[:success] = t('locations.unfollow.success')
    else
      flash[:danger] = t('locations.unfollow.failure')
    end
    redirect_to following_locations_path
  end

  private

  def set_location
    @location = Location.find_by(id: params[:id])
    unless @location
      flash[:danger] = t('locations.location.not_found')
      redirect_to following_locations_path
    end
  end

  def set_follow
    @follow = Follow.find_by(user: current_user, location_id: params[:id])
    unless @follow
      flash[:danger] = t('locations.follow.not_found')
      redirect_to following_locations_path
    end
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = t('users.created')
      redirect_to '/'
    else
      flash[:danger] = t('users.validation_error')
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  
  def new
    redirect_to root_path if current_user
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = t('sessions.create')
      redirect_to root_path
    else
      flash[:danger] = t('sessions.validation_error')
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = t('sessions.delete')
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end
end

app/helpers/account_settings_helper.rb
# frozen_string_literal: true

module AccountSettingsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def active_class?(current_path)
    "active" if current_page?(current_path)
  end
end

app/helpers/locations_helper.rb
# frozen_string_literal: true

module LocationsHelper
  def subscribe_button(location)
    if location.belongs_to_user?(current_user)
      link_to t('locations.index.unfollow'),
              unfollow_locations_path(location.id),
              method: :delete
    else
      link_to t('locations.index.follow'),
              follow_locations_path(location.id)
    end
  end
end

app/helpers/registrations_helper.rb
# frozen_string_literal: true

module RegistrationsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def account_navigation
    if current_user
      link_to t('sessions.form.logout'), logout_path, class: 'nav-link', method: :delete
    else
      link_to t('sessions.form.sign_in_or_sign_up'), login_path, class: 'nav-link'
    end
  end

end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/account_settings/index.html.erb
<div class="container">
  <div class="row">
    <div class="offset-3 col-md-6">
      <div class="card">
        <div class="card-body">
          <h1 class="text-center"><%= t('account_settings.index.header') %></h1>
          <%= link_to t('account_settings.index.remove'), destroy_account_settings_path,
                      class: 'btn btn-danger',
                      data: { confirm: 'Are you sure?' },
                      method: :delete %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherForecastApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <a class="navbar-brand" href="#">WeatherForecastApp</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <% if current_user %>
              <li class="nav-item <%= active_class?(root_path) %>">
                <%= link_to 'Home', root_path, class: 'nav-link'%>
              </li>
              <li class="nav-item <%= active_class?(locations_path) %>">
                <%= link_to 'Browse cities', locations_path, class: 'nav-link'%>
              </li>
              <li class="nav-item <%= active_class?(following_locations_path) %>">
                <%= link_to 'Subscribed', following_locations_path, class: 'nav-link'%>
              </li>
              <li class="nav-item <%= active_class?(account_settings_path) %>">
                <%= link_to 'Account settings', account_settings_path, class: 'nav-link'%>
              </li>
            <% end %>
            <li class="nav-item">
              <%= account_navigation %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container mt-3">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

    <!-- Page Content -->
    <div class="container">
      <div class="vertical-center cover-container">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/locations/_current_weather.html.erb
<p><%= t('locations.following.weather.temperature') %>: <%= location.weather.main.temp %></p>
<p><%= t('locations.following.weather.pressure') %>: <%= location.weather.main.pressure %></p>
<p><%= t('locations.following.weather.humidity') %>: <%= location.weather.main.humidity %></p>

<h3><%= t('locations.following.weather.wind') %></h3>
<p><%= t('locations.following.weather.speed') %>: <%= location.weather.wind.speed %></p>

app/views/locations/following.html.erb
<div class="container">
  <%= render 'shared/header', title: t('locations.following.header') %>
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <% @locations.each do |location| %>
          <div class="col-md-6 mt-3">
            <div class="card weather-card">
              <div class="card-body">
                <h3 class="text-center"><%= location.name %></h1>
                <% if location.weather.status %>
                  <%= render 'current_weather', location: location %>
                <% else %>
                  <p><%= location.weather.message %></p>
                <% end %>
                <%= link_to t('locations.index.unfollow'), unfollow_locations_path(location.id),
                    class: 'btn btn-danger', method: :delete %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-12 mt-3">
      <%= link_to t('locations.following.subscribe'), locations_path,
          class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/locations/index.html.erb
<div class="container">
  <%= render 'shared/header', title: t('locations.index.header') %>
  <div class="row mt-3">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <%= form_tag('/locations', method: :get, id: 'search-form') do %>
          <div class="form-check form-check-inline">
            <%= text_field_tag :query, params[:query], { placeholder: t('locations.index.city'), class: 'form-control' } %>
            <%= submit_tag t('locations.index.search'), class: 'btn btn-info' %>
          </div>
          <% end %>
          <table class="table">
            <thead>
              <tr>
                <th><%= t('locations.index.city') %></th>
                <th><%= t('locations.index.country') %></th>
              </tr>
            </thead>
            <tbody>
              <% @locations.each do |location| %>
                <tr>
                  <td>
                    <%= location.name %>
                    <span class="hint-text">
                      <%= link_to t('locations.index.follow'),
                              follow_locations_path(location.id) %>
                    </span>
                  </td>
                  <td><%= location.country %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= will_paginate @locations %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="form-errors">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="row title-header text-center">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <h1 class="text-center"><%= title %></h1>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="container">
  <h1 class="cover-heading"><%= t('pages.home.main_slogan') %></h1>
  <p class="lead"><%= t('pages.home.lead_content') %></p>
</div>